# TEJTOOLAPI 資料撈取整併
運用 TEJTOOLAPI 整併資料。TEJTOOLAPI 主要整併股價與不同屬性的資料庫，透過輸入股票代碼 (TICKERS) 和欄位 (FIELD) 後，可將欲抓取的資料整併為以日頻率的 DataFrame。

目前可抓取的資料庫為：
- 量化股價([TWN/APIPRCD](https://api.tej.com.tw/columns.html?idCode=TWN/APIPRCD))
- 量化月營收([TWN/APISALE](https://api.tej.com.tw/columns.html?idCode=TWN/APISALE))
- 量化財務([TWN/AFESTM1](https://api.tej.com.tw/columns.html?idCode=TWN/AFESTM1)、[TWN/AINVFINQ](https://api.tej.com.tw/columns.html?idCode=TWN/AINVFINQ)、[TWN/AINVFINQA](https://api.tej.com.tw/columns.html?idCode=TWN/AINVFINQA))
- 量化籌碼_日([TWN/APISHRACT](https://api.tej.com.tw/columns.html?idCode=TWN/APISHRACT))
- 量化籌碼_周[TWN/APISHRACTW](https://api.tej.com.tw/columns.html?idCode=TWN/APISHRACTW))
- 交易註記([TWN/APISTKATTR](https://api.tej.com.tw/columns.html?idCode=TWN/APISTKATTR))
- 交易日期表([TWN/TRADEDAY_TWSE](https://api.tej.com.tw/columns.html?idCode=TWN/TRADEDAY_TWSE))

主要整併方法是以交易日期表為索引整併股價與不同屬性的資料，以下示範 TEJTOOLAPI 整併股價與不同屬性資料表的所有欄位。

tejtoolapi 相關欄位 : https://github.com/tejtw/TQuant-Lab/blob/main/Problem/TEjToolAPI%20%E6%AC%84%E4%BD%8D%E8%B3%87%E8%A8%8A.xlsx<br>

### 1. 環境設定

In [1]:
import os
os.environ['TEJAPI_KEY'] = "your key" 
os.environ['TEJAPI_BASE'] = "https://api.tej.com.tw"

os.environ['ticker'] = '2330 2454 2317 2882 2881'
os.environ['mdate'] = '20000103 20230530'

import TejToolAPI 
from zipline.data import bundles

### 2. 取得 tickers
2.1 取得 bundle 的 tickers

In [2]:
bundle_data = bundles.load('tquant')
universe = bundle_data.asset_finder.retrieve_all(bundle_data.asset_finder.equities_sids)#.remove(symbol('IR0001'))   
tickers = [col.symbol for col in universe]

2.2 自行 key 入 tickers

In [3]:
tickers = ['2330','2454','2317','2882','2881']

### 3. tejtoolapi 取得單獨資料庫

3.1、月營收的欄位

In [4]:
ticker = tickers
columns = ['Sales_Accu_LastYear', 'Sales_Accu_3M',
       'Sales_Per_Share_Accu_12M', 'YoY_Accu_Sales', 'YoY_Monthly_Sales',
       'Sales_Per_Share_Accu_3M', 'Sales_Accu_3M_LastYear', 'Sales_Monthly',
       'YoY_AccuSales_12M', 'YoY_Accu_Sales_3M', 'MoM_Monthly_Sales',
       'Sales_Accumulated', 'QoQ_Accu_Sales_3M', 'MoM_Accu_Sales_3M',
       'Sales_Monthly_LastYear', 'Outstanding_Shares_1000_Shares']

data = TejToolAPI.get_history_data(ticker=ticker, 
                                   columns=columns,
                                   transfer_to_chinese=False,                                   
                                  )
data

,coid,mdate,Outstanding_Shares_1000_Shares,Sales_Per_Share_Accu_12M,YoY_AccuSales_12M,YoY_Monthly_Sales,YoY_Accu_Sales_3M,QoQ_Accu_Sales_3M,Sales_Accu_3M,Sales_Accumulated,YoY_Accu_Sales,Sales_Accu_LastYear,Sales_Monthly_LastYear,Sales_Per_Share_Accu_3M,Sales_Monthly,MoM_Monthly_Sales,Sales_Accu_3M_LastYear,MoM_Accu_Sales_3M
0,2317,2013-01-02,NaN,NaN,17.57,14.50,5.27,22.62,NaN,NaN,16.38,NaN,NaN,NaN,NaN,27.58,NaN,17.52
1,2317,2013-01-03,NaN,NaN,17.57,14.50,5.27,22.62,NaN,NaN,16.38,NaN,NaN,NaN,NaN,27.58,NaN,17.52
2,2317,2013-01-04,NaN,NaN,17.57,14.50,5.27,22.62,NaN,NaN,16.38,NaN,NaN,NaN,NaN,27.58,NaN,17.52
3,2317,2013-01-07,NaN,NaN,17.57,14.50,5.27,22.62,NaN,NaN,16.38,NaN,NaN,NaN,NaN,27.58,NaN,17.52
4,2317,2013-01-08,NaN,NaN,17.57,14.50,5.27,22.62,NaN,NaN,16.38,NaN,NaN,NaN,NaN,27.58,NaN,17.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13210,2882,2023-10-18,14669210.0,18.97,-38.82,-11.71,16.99,-14.51,80363664.0,242661699.0,-20.83,306490720.0,16006854.0,5.48,14132046.0,-42.40,68694456.0,-28.91
13211,2882,2023-10-19,14669210.0,18.97,-38.82,-11.71,16.99,-14.51,80363664.0,242661699.0,-20.83,306490720.0,16006854.0,5.48,14132046.0,-42.40,68694456.0,-28.91
13212,2882,2023-10-20,14669210.0,18.97,-38.82,-11.71,16.99,-14.51,80363664.0,242661699.0,-20.83,306490720.0,16006854.0,5.48,14132046.0,-42.40,68694456.0,-28.91
13213,2882,2023-10-23,14669210.0,18.97,-38.82,-11.71,16.99,-14.51,80363664.0,242661699.0,-20.83,306490720.0,16006854.0,5.48,14132046.0,-42.40,68694456.0,-28.91
13214,2882,2023-10-24,14669210.0,18.97,-38.82,-11.71,16.99,-14.51,80363664.0,242661699.0,-20.83,306490720.0,16006854.0,5.48,14132046.0,-42.40,68694456.0,-28.91

3.2、量化籌碼_周 - 集保庫存欄位

In [5]:
ticker = tickers
columns = ['Total_Custodied_Shares_1000_Lots',
       'Custodied_Under_400_Lots_Total_Lots',
       'Custodied_Lots_Between_800_1000_Total_Lots',
       'Custodied_Larger_Than_400_Lots_Pct',
       'Custodied_Lots_Between_400_600_Total_Lots',
       'Custodied_Lots_Between_600_800_Pct', 'Pledged_Stock_Shares_1000_Lots',
       'Custodied_Under_400_Lots_Pct',
       'Custodied_Lots_Between_400_600_Total_Holders',
       'Custodied_Lots_Between_800_1000_Total_Holders',
       'Custodied_Under_400_Lots_Total_Holders',
       'Custodied_Lots_Between_400_600_Pct',
       'Custodied_Lots_Between_800_1000_Pct',
       'Custodied_Greater_Than_1000_Lots_Pct']

data1 = TejToolAPI.get_history_data(ticker=ticker, 
                                   columns=columns,
                                   transfer_to_chinese=False,                                    
                                  )                                 
    
data1

,coid,mdate,Custodied_Under_400_Lots_Pct,Custodied_Lots_Between_400_600_Total_Lots,Custodied_Lots_Between_600_800_Pct,Custodied_Lots_Between_400_600_Pct,Custodied_Under_400_Lots_Total_Holders,Custodied_Lots_Between_800_1000_Pct,Custodied_Lots_Between_800_1000_Total_Holders,Custodied_Under_400_Lots_Total_Lots,Custodied_Lots_Between_400_600_Total_Holders,Custodied_Lots_Between_800_1000_Total_Lots,Custodied_Greater_Than_1000_Lots_Pct,Custodied_Larger_Than_400_Lots_Pct,Pledged_Stock_Shares_1000_Lots,Total_Custodied_Shares_1000_Lots
0,2317,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,623341.0,11835866.0
1,2317,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,623341.0,11835866.0
2,2317,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,623341.0,11835866.0
3,2317,2013-01-07,21.45,161668.0,1.17,1.36,480870.0,1.05,139.0,2545704.0,327.0,125000.0,74.89,78.47,633326.0,11835866.0
4,2317,2013-01-08,21.45,161668.0,1.17,1.36,480870.0,1.05,139.0,2545704.0,327.0,125000.0,74.89,78.47,633326.0,11835866.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13210,2882,2023-10-18,20.76,157125.0,0.82,1.07,512814.0,0.67,110.0,3053761.0,322.0,98536.0,76.61,79.17,2180654.0,14669210.0
13211,2882,2023-10-19,20.76,157125.0,0.82,1.07,512814.0,0.67,110.0,3053761.0,322.0,98536.0,76.61,79.17,2180654.0,14669210.0
13212,2882,2023-10-20,20.76,157125.0,0.82,1.07,512814.0,0.67,110.0,3053761.0,322.0,98536.0,76.61,79.17,2180654.0,14669210.0
13213,2882,2023-10-23,20.73,155473.0,0.82,1.05,512357.0,0.69,113.0,3050574.0,319.0,101329.0,76.62,79.18,2180718.0,14669210.0
13214,2882,2023-10-24,20.73,155473.0,0.82,1.05,512357.0,0.69,113.0,3050574.0,319.0,101329.0,76.62,79.18,2180718.0,14669210.0

3.3、量化籌碼_日& 交易註記 欄位

In [6]:
ticker = tickers
columns =['Market', 'Dealer_Proprietary_Diff_Vol', 'Margin_Sale',
       'Cash_Redemption', 'Margin_Short_Balance_Amt',
       'Margin_Short_Balance_Vol', 'Dealer_Hedge_Buy_Vol',
       'Day_Trading_Volume_1000_Shares', 'SBL_Short_Returns_Vol',
       'Margin_Maintenance_Ratio', 'Account_Maintenance_Ratio',
       'Margin_Stock_Redemtion', 'Total_Sell_Amt',
       'Margin_Short_Maintenance_Ratio', 'SBL_Short_Balance_Vol',
       'Dealer_Hedge_Buy_Amt', 'Total_Buy_Amt', 'Total_Diff_Amt',
       'Fund_Diff_Vol', 'Dealer_Proprietary_Buy_Vol',
       'Dealer_Proprietary_Sell_Amt', 'Margin_Day_Trading_Amt',
       'Total_Diff_Vol', 'SBL_Short_Sales_Vol', 'SBL_Short_Balance_Amt',
       'Dealer_Stock_Holding_Pct', 'Dealer_Hedge_Sell_Vol', 'Qfii_Buy_Vol',
       'Qfii_Stock_Holding_Pct', 'Qfii_Sell_Vol', 'Fund_Stock_Holding_Pct',
       'Dealer_Proprietary_Buy_Amt', 'Dealer_Hedge_Diff_Amt', 'Qfii_Sell_Amt',
       'Margin_Day_Trading_Vol', 'Fund_Sell_Amt', 'Day_Trading_Pct',
       'Margin_Short_Sales', 'Fund_Diff_Amt', 'Margin_Balance_Ratio',
       'SBL_Short_Sales_Amt', 'Fund_Buy_Vol', 'Qfii_Buy_Amt',
       'Margin_Balance_Vol', 'Qfii_Diff_Vol', 'Margin_Purchase',
       'Dealer_Hedge_Sell_Amt', 'Dealer_Proprietary_Sell_Vol', 'Fund_Sell_Vol',
       'Margin_Quota', 'Qfii_Diff_Amt', 'Total_Sell_Vol', 'Margin_Short_Quota',
       'Margin_Short_Coverting', 'Fund_Buy_Amt', 'Dealer_Proprietary_Diff_Amt',
       'Total_Buy_Vol', 'Margin_Balance_Amt', 'SBL_Short_Quota',
       'Dealer_Hedge_Diff_Vol', 'Component_Stock_of_TPEx200_Fg', 'Industry',
       'Component_Stock_of_MSCI_TW_Fg', 'Component_Stock_of_High_Dividend_Fg',
       'Security_Type_Chinese', 'Suspension_of_Buy_After_Day_Trading_Fg',
       'Matching_Period', 'Component_Stock_of_TWN50_Fg',
       'Component_Stock_of_MidCap100_Fg', 'Suspended_Trading_Stock_Fg',
       'Market_Board', 'Full_Delivery_Stock_Fg', 'Disposition_Stock_Fg',
       'Security_Type_English', 'Attention_Stock_Fg', 'Industry_Eng',
       'Component_Stock_of_TPEx50_Fg', 'Limit_Up_or_Down_in_Opening_Fg',
       'Limit_Up_or_Down']

data2 = TejToolAPI.get_history_data(ticker=tickers, 
                                    columns=columns,
                                    transfer_to_chinese=False,                                    
                                   )                                 
    
data2

,coid,mdate,Listing_Type,Limit_Up_or_Down_in_Opening_Fg,Security_Type_English,Component_Stock_of_MidCap100_Fg,Limit_Up_or_Down,Component_Stock_of_MSCI_TW_Fg,Suspended_Trading_Stock_Fg,Industry,...,Day_Trading_Volume_1000_Shares,Total_Diff_Vol,Dealer_Proprietary_Buy_Vol,Margin_Short_Balance_Amt,Margin_Balance_Amt,Account_Maintenance_Ratio,Qfii_Stock_Holding_Pct,Margin_Short_Coverting,Margin_Day_Trading_Vol,SBL_Short_Sales_Vol
0,2317,2013-01-02,TWSE,,Common Stock,,,Y,,M2331 其他電子業指數,...,NaN,-3115.0,NaN,411762.12,9445508.60,164.99,48.65,97.0,750.0,6.0
1,2317,2013-01-03,TWSE,,Common Stock,,,Y,,M2331 其他電子業指數,...,NaN,-1655.0,NaN,480954.00,9397992.70,166.01,48.66,101.0,1136.0,0.0
2,2317,2013-01-04,TWSE,,Common Stock,,,Y,,M2331 其他電子業指數,...,NaN,-9610.0,NaN,488592.97,9341749.48,164.49,48.59,353.0,842.0,107.0
3,2317,2013-01-07,TWSE,,Common Stock,,,Y,,M2331 其他電子業指數,...,NaN,-22566.0,NaN,495856.76,9586680.16,162.84,48.45,976.0,875.0,85.0
4,2317,2013-01-08,TWSE,,Common Stock,,,Y,,M2331 其他電子業指數,...,NaN,-17842.0,NaN,319181.95,9937151.65,162.52,48.33,2151.0,1535.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13210,2882,2023-10-18,TWSE,,Common Stock,,,Y,,M2800 金融保險類指數,...,3149.0,4511.0,660.0,35634.88,613438.73,170.87,21.24,12.0,0.0,849.0
13211,2882,2023-10-19,TWSE,,Common Stock,,,Y,,M2800 金融保險類指數,...,2737.0,-913.0,99.0,34889.51,612484.66,169.29,21.20,31.0,0.0,332.0
13212,2882,2023-10-20,TWSE,,Common Stock,,,Y,,M2800 金融保險類指數,...,8875.0,-5455.0,270.0,36712.43,605111.44,168.20,21.15,59.0,11.0,2674.0
13213,2882,2023-10-23,TWSE,,Common Stock,,,Y,,M2800 金融保險類指數,...,2575.0,-5048.0,138.0,35537.93,612675.61,166.31,21.11,34.0,0.0,2587.0
13214,2882,2023-10-24,TWSE,,Common Stock,,,Y,,M2800 金融保險類指數,...,2026.0,-2132.0,35.0,35467.50,613843.53,166.47,21.09,8.0,0.0,1728.0

3.4、抓取財務資料參數設定

`ticker`
- 單一股票  :['2330'] 
- 多股      :['2330','2317']

`columns`
- 欄位: columns=['r408','r409','r410','r502']

`transfer_chinese_columns`
- 預設 transfer_chinese_columns = False
- 測試欄位轉換成中文(transfer_chinese_columns = True)

`fin_type = [A, Q, TTM]`
- A: 表示累積
- Q: 表示單季
- TTM: 表示移動4季

`include_self_acc`
- 投資用財務包含自結和董事會決議數(include_self_acc = 'Y')
- 僅投資用財務(include_self_acc = 'N')

3.4.1、財務僅會計師核閱

In [7]:
columns =['Total_Operating_Cost','Sales_Per_Share','Return_Rate_on_Equity_A_percent',
       'Proceeds_from_Disposal_of_Fixed_and_Intangible_Assets',
       'Cash_Flow_from_Operating_Activities', 
       'Other_Adjustment_from_Operating_Activities', 'Borrowings',       
       'Total_Operating_Expenses', 'Gross_Margin_Rate_percent',
       'Sales_Growth_Rate', 'Net_Income_Per_Share','Total_Assets',
       'Short_Term_Borrowings_Financial_Institutions',
       'Pre_Tax_Income_Growth_Rate', 'Total_Equity_Growth_Rate',
       'Total_Operating_Income','Total_Assets_Turnover',
       'Operating_Income_Per_Share','Pre_Tax_Income_Rate_percent', 
       'Gross_Profit_Loss_from_Operations','Return_on_Total_Assets',
       'Depreciation_and_Amortisation','Total_Interest_Income',
       'Fixed_Asset_Turnover', 'Decrease_Increase_in_Prepayments',]

fin_type = ['A','Q','TTM']

data = TejToolAPI.get_history_data(ticker=tickers, columns=columns, transfer_to_chinese=False, fin_type=fin_type, include_self_acc='N')
data

,coid,mdate,Depreciation_and_Amortisation_A,Depreciation_and_Amortisation_Q,Depreciation_and_Amortisation_TTM,Pre_Tax_Income_Rate_percent_A,Pre_Tax_Income_Rate_percent_Q,Pre_Tax_Income_Rate_percent_TTM,Net_Income_Per_Share_A,Net_Income_Per_Share_Q,...,Gross_Profit_Loss_from_Operations_TTM,Short_Term_Borrowings_Financial_Institutions_A,Short_Term_Borrowings_Financial_Institutions_Q,Short_Term_Borrowings_Financial_Institutions_TTM,Total_Equity_Growth_Rate_A,Total_Equity_Growth_Rate_Q,Total_Equity_Growth_Rate_TTM,Total_Assets_A,Total_Assets_Q,Total_Assets_TTM
0,2317,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2317,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2317,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2317,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2317,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13210,2882,2023-10-18,4220266.0,2115580.0,8156487.0,23.81,33.43,9.34,2.25,1.76,...,120279837.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13211,2882,2023-10-19,4220266.0,2115580.0,8156487.0,23.81,33.43,9.34,2.25,1.76,...,120279837.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13212,2882,2023-10-20,4220266.0,2115580.0,8156487.0,23.81,33.43,9.34,2.25,1.76,...,120279837.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13213,2882,2023-10-23,4220266.0,2115580.0,8156487.0,23.81,33.43,9.34,2.25,1.76,...,120279837.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13214,2882,2023-10-24,4220266.0,2115580.0,8156487.0,23.81,33.43,9.34,2.25,1.76,...,120279837.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10

3.4.2、財務包含公司自結數與會計師核閱

In [8]:
columns =['Total_Operating_Cost','Sales_Per_Share','Return_Rate_on_Equity_A_percent',
       'Proceeds_from_Disposal_of_Fixed_and_Intangible_Assets',
       'Cash_Flow_from_Operating_Activities', 
       'Other_Adjustment_from_Operating_Activities', 'Borrowings',       
       'Total_Operating_Expenses', 'Gross_Margin_Rate_percent',
       'Sales_Growth_Rate', 'Net_Income_Per_Share','Total_Assets',
       'Short_Term_Borrowings_Financial_Institutions',
       'Pre_Tax_Income_Growth_Rate', 'Total_Equity_Growth_Rate',
       'Total_Operating_Income','Total_Assets_Turnover',
       'Operating_Income_Per_Share','Pre_Tax_Income_Rate_percent', 
       'Gross_Profit_Loss_from_Operations','Return_on_Total_Assets',
       'Depreciation_and_Amortisation','Total_Interest_Income',
       'Fixed_Asset_Turnover', 'Decrease_Increase_in_Prepayments',]

fin_type = ['A','Q','TTM']

data = TejToolAPI.get_history_data(ticker=tickers, columns=columns, transfer_to_chinese=True, fin_type=fin_type, include_self_acc='Y')
data

,公司簡稱,目前狀態,營業總收入_A,營業總收入_Q,營業總收入_TTM,營收成長率_A,營收成長率_Q,營收成長率_TTM,稅前淨利成長率_A,稅前淨利成長率_Q,...,營業總成本_TTM,金融借款_流動_A,金融借款_流動_Q,金融借款_流動_TTM,淨值成長率_A,淨值成長率_Q,淨值成長率_TTM,資產總計_A,資產總計_Q,資產總計_TTM
0,2317,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2317,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2317,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2317,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2317,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13210,2882,2023-10-18,162412481.0,94002234.0,266049874.0,-20.83,16.82,-38.97,-0.26,351.52,...,145770037.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13211,2882,2023-10-19,162412481.0,94002234.0,266049874.0,-20.83,16.82,-38.97,-0.26,351.52,...,145770037.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13212,2882,2023-10-20,162412481.0,94002234.0,266049874.0,-20.83,16.82,-38.97,-0.26,351.52,...,145770037.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13213,2882,2023-10-23,162412481.0,94002234.0,266049874.0,-20.83,16.82,-38.97,-0.26,351.52,...,145770037.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10
13214,2882,2023-10-24,162412481.0,94002234.0,266049874.0,-20.83,16.82,-38.97,-0.26,351.52,...,145770037.0,64446512.0,64446512.0,64446512.0,59.63,59.63,59.63,1.270923e+10,1.270923e+10,1.270923e+10

### 4、以下範例示範運用 TejToolAPI U 一鍵抓取不同資料庫的欄位與整併。
- **股價資料庫(日頻)**
    - 開盤價、收盤價
- **籌碼資料庫(日頻)**
    - 外資買賣超張數、合計買賣超張數
- **交易註記資料庫(日頻)**
    - 是否為注意股票、是否暫停交易、是否為臺灣50成分股、是否為處置股票、分盤間隔時間
- **集保資料庫(周頻)**
    - 800-1000張集保占比、800-1000張集保張數    
- **財報資料庫(季頻)**
    - 營業毛利成長率_Q、營業利益成長率_Q、稅後淨利率_Q

In [14]:
# 輸入欄位
icolumns = ['Open','Close','Qfii_Diff_Vol','Total_Diff_Vol','Custodied_Lots_Between_800_1000_Total_Lots','Custodied_Lots_Between_800_1000_Pct',
           'Attention_Stock_Fg','Disposition_Stock_Fg','Matching_Period','Suspended_Trading_Stock_Fg','Component_Stock_of_TWN50_Fg','Gross_Margin_Growth_Rate','Net_Income_Rate_percent','Operating_Income_Growth_Rate']
# TEJTOOLAPI整併
data = TejToolAPI.get_history_data(ticker=tickers[:5], 
                                   columns=icolumns,
                                   transfer_to_chinese=True, 
                                   fin_type = ['Q'],
                                   start = '2015-01-01', end = '2022-12-31')
data#.sort_values(by=['日期','股票代碼']).tail(10)

,公司簡稱,目前狀態,是否暫停交易,是否為處置股票,是否為注意股票,分盤間隔時間,是否為臺灣50成分股,開盤價,收盤價,外資買賣超張數,合計買賣超張數,800_1000張集保占比,800_1000張集保張數,營業利益成長率_Q,稅後淨利率_Q,營業毛利成長率_Q
0,2317,2015-01-05,,,,0.0,Y,87.80,87.20,-11284.0,-12896.0,0.76,113381.0,-1.49,3.64,3.84
1,2317,2015-01-06,,,,0.0,Y,86.00,84.50,-34944.0,-38928.0,0.76,113381.0,-1.49,3.64,3.84
2,2317,2015-01-07,,,,0.0,Y,84.30,85.20,-8780.0,-9110.0,0.76,113381.0,-1.49,3.64,3.84
3,2317,2015-01-08,,,,0.0,Y,85.90,86.90,4228.0,7187.0,0.76,113381.0,-1.49,3.64,3.84
4,2317,2015-01-09,,,,0.0,Y,87.30,86.50,-2308.0,-4927.0,0.76,113381.0,-1.49,3.64,3.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9785,2882,2022-12-26,,,,0.0,Y,41.15,41.00,-2951.0,-1030.0,0.74,97837.0,-79.09,7.52,-45.94
9786,2882,2022-12-27,,,,0.0,Y,41.00,41.15,2282.0,3892.0,0.74,97837.0,-79.09,7.52,-45.94
9787,2882,2022-12-28,,,,0.0,Y,40.85,40.65,-620.0,18.0,0.74,97837.0,-79.09,7.52,-45.94
9788,2882,2022-12-29,,,,0.0,Y,40.50,40.10,-1219.0,-1446.0,0.74,97837.0,-79.09,7.52,-45.94
9789,2882,2022-12-30,,,,0.0,Y,39.75,40.00,21840.0,49454.0,0.71,104859.0,-79.09,7.52,-45.94

抓取股價資料庫與籌碼料庫

In [15]:
columns = ['Open','High','Low','Close','Adjust_Factor','Volume_1000_Shares','Value_Dollars'
           'Transaction','Last_Bid','Last_Offer','Average_Trade_Price','ROI','High_Low_Diff','Turnover'
           'Issue_Shares_1000_Shares','Market_Cap_Dollars','Market_Cap_Percentage','Trade_Value_Percentage'
           'PER_TWSE','PBR_TWSE','Dividend_Yield_TWSE','Cash_Dividend_Yield_TEJ',
           'Qfii_Buy_Vol','Qfii_Sell_Vol','Qfii_Diff_Vol','Qfii_Buy_Amt','Qfii_Sell_Amt','Qfii_Diff_Amt','Qfii_Stock_Holding_Pct','Fund_Buy_Vol',
           'Fund_Sell_Vol','Fund_Diff_Vol','Fund_Buy_Amt','Fund_Sell_Amt','Fund_Diff_Amt','Fund_Stock_Holding_Pct','Dealer_Proprietary_Buy_Vol','Dealer_Proprietary_Sell_Vol','Dealer_Proprietary_Diff_Vol','Dealer_Proprietary_Buy_Amt',
           'Dealer_Proprietary_Sell_Amt','Dealer_Proprietary_Diff_Amt','Dealer_Hedge_Buy_Vol','Dealer_Hedge_Sell_Vol','Dealer_Hedge_Diff_Vol','Dealer_Hedge_Buy_Amt','Dealer_Hedge_Sell_Amt','Dealer_Hedge_Diff_Amt',
           'Dealer_Stock_Holding_Pct','Total_Buy_Vol','Total_Sell_Vol','Total_Diff_Vol','Total_Buy_Amt','Total_Sell_Amt','Total_Diff_Amt'
            ]
data = TejToolAPI.get_history_data(ticker=ticker, 
                                   columns=columns,
                                   transfer_to_chinese=False, 
                                   start = '2015-01-01', end = '2022-12-31')
data

,coid,mdate,PBR_TWSE,High_Low_Diff,Open,Volume_1000_Shares,Last_Bid,Low,Last_Offer,ROI,...,Total_Sell_Vol,Total_Diff_Amt,Fund_Diff_Amt,Dealer_Hedge_Buy_Amt,Qfii_Sell_Amt,Dealer_Proprietary_Diff_Amt,Total_Sell_Amt,Total_Diff_Vol,Dealer_Proprietary_Buy_Vol,Qfii_Stock_Holding_Pct
0,1101,2015-01-05,1.42,1.3825,43.40,2842.0,43.00,42.80,43.10,-0.9217,...,1970.0,-43215.0,0.0,43.0,82818.0,-602.0,84710.0,-1005.0,0.0,35.82
1,1101,2015-01-06,1.40,1.1628,42.50,7654.0,42.25,42.10,42.30,-1.7442,...,5890.0,-106681.0,0.0,42.0,243276.0,-930.0,248853.0,-2525.0,0.0,35.76
2,1101,2015-01-07,1.39,1.6568,42.25,8719.0,42.10,41.85,42.15,-0.3550,...,7013.0,-241738.0,2610.0,2863.0,273524.0,421.0,295247.0,-5742.0,10.0,35.61
3,1101,2015-01-08,1.40,1.3064,42.25,8697.0,42.25,42.10,42.40,0.3563,...,7385.0,-216362.0,-31688.0,4859.0,276062.0,1056.0,312016.0,-5121.0,30.0,35.49
4,1101,2015-01-09,1.38,1.8935,42.30,10494.0,41.75,41.80,41.80,-1.0651,...,9825.0,-334149.0,-5977.0,920.0,396264.0,84.0,410685.0,-7994.0,2.0,35.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7827,9958,2022-12-26,2.80,3.7120,88.40,3690.0,86.20,85.70,86.40,-3.0371,...,1237.0,-73701.0,0.0,259.0,94734.0,5086.0,106629.0,-855.0,62.0,8.06
7828,9958,2022-12-27,2.86,2.6682,86.20,1874.0,87.90,86.20,88.00,2.0882,...,362.0,25608.0,0.0,4752.0,30184.0,13112.0,31856.0,291.0,151.0,8.06
7829,9958,2022-12-28,2.98,6.0227,88.00,10025.0,91.90,87.70,92.00,4.4318,...,1469.0,235480.0,27570.0,28581.0,110372.0,-19575.0,135001.0,2562.0,16.0,8.80
7830,9958,2022-12-29,2.95,3.6997,90.90,7057.0,90.70,88.80,90.80,-1.1970,...,2108.0,-46938.0,18160.0,13892.0,157169.0,-5811.0,191401.0,-517.0,2.0,8.52
7831,9958,2022-12-30,2.87,2.8634,90.90,4649.0,88.60,88.60,88.70,-2.4229,...,2486.0,-175162.0,22150.0,2747.0,214501.0,12050.0,220260.0,-1977.0,137.0,7.35

抓取財務資料(default:僅會計師核閱)

In [16]:
ticker = ['2881', '1101','9958','2330']
columns = ['r404','r401','eps']
fin_type = ['A','Q','TTM']
data = TejToolAPI.get_history_data(ticker=ticker, columns=columns,transfer_to_chinese=True, fin_type=fin_type)
data

,公司簡稱,目前狀態,營收成長率_A,營收成長率_Q,營收成長率_TTM,稅前淨利成長率_A,稅前淨利成長率_Q,稅前淨利成長率_TTM,母公司每股盈餘_A,母公司每股盈餘_Q,母公司每股盈餘_TTM
0,1101,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1101,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1101,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1101,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1101,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10567,9958,2023-10-18,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10568,9958,2023-10-19,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10569,9958,2023-10-20,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10570,9958,2023-10-23,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10571,9958,2023-10-24,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27

抓取財務資料僅會計師核閱

In [17]:
ticker = ['2881', '1101','9958','2330']
columns = ['r404','r401','eps']
fin_type = ['A','Q','TTM']
data = TejToolAPI.get_history_data(ticker=ticker, columns=columns,transfer_to_chinese=True, fin_type=fin_type, include_self_acc='N')
data

,公司簡稱,目前狀態,營收成長率_A,營收成長率_Q,營收成長率_TTM,稅前淨利成長率_A,稅前淨利成長率_Q,稅前淨利成長率_TTM,母公司每股盈餘_A,母公司每股盈餘_Q,母公司每股盈餘_TTM
0,1101,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1101,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1101,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1101,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1101,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10567,9958,2023-10-18,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10568,9958,2023-10-19,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10569,9958,2023-10-20,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10570,9958,2023-10-23,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10571,9958,2023-10-24,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27

抓取財務資料含自結數

In [18]:
ticker = ['2881', '1101','9958','2330']
columns = ['r404','r401','eps']
fin_type = ['A','Q','TTM']
data = TejToolAPI.get_history_data(ticker=ticker, columns=columns, transfer_to_chinese=True, fin_type=fin_type, include_self_acc='Y')
data

,公司簡稱,目前狀態,營收成長率_A,營收成長率_Q,營收成長率_TTM,稅前淨利成長率_A,稅前淨利成長率_Q,稅前淨利成長率_TTM,母公司每股盈餘_A,母公司每股盈餘_Q,母公司每股盈餘_TTM
0,1101,2013-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1101,2013-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1101,2013-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1101,2013-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1101,2013-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10567,9958,2023-10-18,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10568,9958,2023-10-19,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10569,9958,2023-10-20,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10570,9958,2023-10-23,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27
10571,9958,2023-10-24,48.67,84.9,13.05,-44.39,549.26,-102.6,1.2,0.99,1.27